### PR TITLE
Added support for SonarQube 8.0-8.8

### PR DESCRIPTION
**Pull request by kcbaltz**
Added an 8.0 requester and the ability to override the URL for obtaining component info.

### CODE REVIEW

**Comment by dvelardez** [comment]
Have you been able to successfully test this PR? This is my console output:

Started by user Ciberapps Admin
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/workspace/test-sonar-quality-gates
org.quality.gates.jenkins.plugin.QGException: Expected status 200, got: 400. Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Unknown Reason</title>
</head><body>
<h1>Unknown Reason</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

	at org.quality.gates.sonar.api.SonarHttpRequester.executeGetRequest(SonarHttpRequester.java:128)
	at org.quality.gates.sonar.api.SonarHttpRequester.getComponentId(SonarHttpRequester.java:186)
	at org.quality.gates.sonar.api60.SonarHttpRequester60.getSonarApiTaskInfoParameter(SonarHttpRequester60.java:39)
	at org.quality.gates.sonar.api.SonarHttpRequester.getAPITaskInfo(SonarHttpRequester.java:149)
	at org.quality.gates.sonar.api.QualityGatesProvider.getAPIResultsForQualityGates(QualityGatesProvider.java:62)
	at org.quality.gates.jenkins.plugin.BuildDecision.getStatus(BuildDecision.java:24)
	at org.quality.gates.jenkins.plugin.QGPublisher.perform(QGPublisher.java:85)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1835)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Quality Gates Sonarqube Plugin' marked build as failure
Finished: FAILURE

**Comment by kcbaltz** [comment]
The PR builds locally for me with `mvn clean test` and GitHub was able to verify it: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fsonar-quality-gates-plugin/detail/PR-17/2/pipeline

We're using this patched version of the plugin with our local Jenkins and SQ 8.0 and not having any issues.

Your trace suggests the plugin thinks it's talking to a 6.0 version of SonarQube.  What version do you have?  I don't have a 6.0 to test with.     If you're using something more recent, there could be a bug in my code.    

Try hitting the following URL and sharing the result.  https://<your sonarqube server>/api/server/version

**Comment by dvelardez** [comment]
I am using SonarQube 8.0
Here the result of the version:
8.0.0.29455

**Comment by kcbaltz** [comment]
Just so I can understand what's happening: I'm assuming you've downloaded my fork of this plugin and built it locally and then installed the plugin in your Jenkins and run a job that analyzed a project and attempted to upload the results, causing the trace that you uploaded?   Is that all correct? That error your hitting could also be the result of running the existing version of the plugin without my PR.

**Comment by wissemwis** [comment]
Hello,
when is this release scheduled please ?

**Comment by kcbaltz** [comment]
I don't control the project so I can't help with an official release. However, i could share my locally built .hpi that we're using.  Let me know.

**Comment by EikeDawid** [comment]
Thank you @kcbaltz ! 
We switched to your fork and it is working well with Sonar 8.0.

**Comment by rimuln** [comment]
If I'm right your fix will works for 8.0-8.7.x ? In 8.8 componentId resp. componentKey was removed and only valid parameter is component: 

so like this: SONAR_API_TASK_INFO = "/api/ce/component?component=%s";

**Comment by kcbaltz** [comment]
Thanks for the info.  We're still on 8.6.1 so we haven't seen this issue yet.  I'll look at patching this when our ops group starts the 8.8 rollout process.

**Comment by rimuln** [comment]
I was probably to fast with PR. First run on our jenkins and sonar end with same error. So next attempt with some logging. Probably I could have wrong decision. But build takes cca 1 hour. so not easy debug (

**Comment by rimuln** [comment]
Hmm. Maybe others know but me not. I still fight yeasterday with problem, that althought I fixed locally plugin to Sonar 8.8 in Factory it still use class for 6.1. Today found reason. On FS in job folder is file config.xml where is hardcoded class for it.
`    <org.quality.gates.jenkins.plugin.QGPublisher plugin="sonar-quality-gates@1.3.1">
      <jobConfigData>
        <projectKey>de.ids.acos.et:acoset-parent</projectKey>
        <sonarInstanceName>SonarQube@sonarqube.ids.de</sonarInstanceName>
        <buildStatus>UNSTABLE</buildStatus>
      </jobConfigData>
      <buildDecision>
        <qualityGatesProvider>
          <qualityGateResponseParser/>
          <sonarHttpRequester class="org.quality.gates.sonar.api61.SonarHttpRequester61">
            <logged>false</logged>
          </sonarHttpRequester>
          <sonarInstanceValidationService/>
        </qualityGatesProvider>
      </buildDecision>
      <jobConfigurationService/>
      <jobExecutionService/>
    </org.quality.gates.jenkins.plugin.QGPublisher>`

**Comment by ccHanibal** [comment]
We ran into the same issue after migration to sonar 8.9 LTS.

I can confirm that the fork from @rimuln works.  
For existing projects one has to remove the quality gates step. then save and add it back in, so that the config.xml file get rewiritten. A little tedious to do it for all jobs, but it's ok.

**Comment by vipulmadaan** [comment]
@kcbaltz 
Could you please help me, I tried to repackage your fork and getting below error:
ERROR: [flexible-publish] Quality Gates Sonarqube Plugin (org.quality.gates.jenkins.plugin.QGPublisher@26c25894) aborted due to exception
java.lang.NullPointerException
	at org.quality.gates.sonar.api.SonarInstanceValidationService.validateData(SonarInstanceValidationService.java:53)
	at org.quality.gates.sonar.api.QualityGatesProvider.getAPIResultsForQualityGates(QualityGatesProvider.java:42)
	at org.quality.gates.jenkins.plugin.BuildDecision.getStatus(BuildDecision.java:24)
	at org.quality.gates.jenkins.plugin.QGPublisher.perform(QGPublisher.java:85)
	at org.jenkins_ci.plugins.flexible_publish.builder.FailAtEndBuilder.perform(FailAtEndBuilder.java:104)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.run(BuildStepRunner.java:110)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$Fail.conditionalRun(BuildStepRunner.java:154)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
	at org.jenkins_ci.plugins.flexible_publish.strategy.FailAtEndExecutionStrategy.perform(FailAtEndExecutionStrategy.java:85)
	at org.jenkins_ci.plugins.flexible_publish.ConditionalPublisher.perform(ConditionalPublisher.java:206)
	at org.jenkins_ci.plugins.flexible_publish.FlexiblePublisher.perform(FlexiblePublisher.java:124)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1881)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)

**Comment by kcbaltz** [comment]
@vipulmadaan  This fork only handles up to 8.7 (or maybe 8.8).  I don't have an 8.9 instance to test with, so i haven't updated it yet.  Please see other comments from @rimuln  who has another method for later versions.

**Comment by rimuln** [comment]
yes my fork and branch sonar-88 works with sonarqube 8.8. And I use it on 8.9.1 too.

**Comment by vipulmadaan** [comment]
Thank you so much  @kcbaltz and @rimuln 
I am trying to compile sonar88 branch from https://github.com/rimuln/sonar-quality-gates-plugin/tree/sonar-88. Will let you know the outcome.

**Comment by vipulmadaan** [comment]
Got same error .
Sonar version
Developer EditionVersion 8.9.2 (build 46101)

org.quality.gates.jenkins.plugin.QGException: Expected status 200, got: 400. Response: {"errors":[{"msg":"The \u0027component\u0027 parameter is missing"}]}
	at org.quality.gates.sonar.api.SonarHttpRequester.executeGetRequest(SonarHttpRequester.java:128)
	at org.quality.gates.sonar.api.SonarHttpRequester.getAPITaskInfo(SonarHttpRequester.java:155)
	at org.quality.gates.sonar.api.QualityGatesProvider.getAPIResultsForQualityGates(QualityGatesProvider.java:62)
	at org.quality.gates.jenkins.plugin.BuildDecision.getStatus(BuildDecision.java:24)
	at org.quality.gates.jenkins.plugin.QGPublisher.perform(QGPublisher.java:85)
	at org.jenkins_ci.plugins.flexible_publish.builder.FailAtEndBuilder.perform(FailAtEndBuilder.java:104)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.run(BuildStepRunner.java:110)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$Fail.conditionalRun(BuildStepRunner.java:154)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
	at org.jenkins_ci.plugins.flexible_publish.strategy.FailAtEndExecutionStrategy.perform(FailAtEndExecutionStrategy.java:85)
	at org.jenkins_ci.plugins.flexible_publish.ConditionalPublisher.perform(ConditionalPublisher.java:206)
	at org.jenkins_ci.plugins.flexible_publish.FlexiblePublisher.perform(FlexiblePublisher.java:124)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1881)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)

**Comment by rimuln** [comment]
Check your jenkins config. what I remember in job configuration is saved concrete factory class:(. if it doesn't contains in name 88 then your job stills use the older file that isn't compatible.

**Comment by vipulmadaan** [comment]
> Check your jenkins config. what I remember in job configuration is saved concrete factory class:(. if it doesn't contains in name 88 then your job stills use the older file that isn't compatible.

Thank you so much. This was the issue. It worked like a cham.

**Comment by Bijaya196** [comment]
Hello  
  I  am using  free style job , while sonar scanner is passing  but  when i  tried for quality  gate thowing error .
 INFO] Analysis report generated in 163ms, dir size=1 MB
[INFO] Analysis report compressed in 317ms, zip size=520 KB
[INFO] Analysis report generated in /var/lib/jenkins/workspace/Sonar quality_gate/Java/tta-admin/target/sonar/scanner-report
[INFO] Analysis report uploaded in 58ms
[INFO] ANALYSIS SUCCESSFUL, you can browse http://10.0.1.164/dashboard?id=com.daimler.tta%3Atta-admin
[INFO] Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
[INFO] More about the report processing at http://10.0.1.164/api/ce/task?id=AXxax7hmQ3kbVunvK0lK
[INFO] Analysis total time: 34.109 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:01 min
[INFO] Finished at: 2021-10-07T18:13:30+05:30
[INFO] ------------------------------------------------------------------------
quality.gates.jenkins.plugin.QGException: Expected status 200, got: 401. Response: 
	at quality.gates.sonar.api.SonarHttpRequester.executeGetRequest(SonarHttpRequester.java:59)
	at quality.gates.sonar.api.SonarHttpRequester.getAPIInfo(SonarHttpRequester.java:47)
	at quality.gates.sonar.api.QualityGatesProvider.getRequesterResult(QualityGatesProvider.java:34)
	at quality.gates.sonar.api.QualityGatesProvider.getAPIResultsForQualityGates(QualityGatesProvider.java:29)
	at quality.gates.jenkins.plugin.BuildDecision.getStatus(BuildDecision.java:20)
	at quality.gates.jenkins.plugin.QGPublisher.perform(QGPublisher.java:73)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:21)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:808)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:757)
	at hudson.model.Build$BuildExecution.post2(Build.java:179)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:701)
	at hudson.model.Run.execute(Run.java:1914)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
Build step 'Quality Gates' marked build as failure
Posting build status of FAILED to Bitbucket for commit id [f7237067e6d7048b612844e3a16368f564891707] and ref 'null'
Finished: FAILURE

**Comment by alexanderjohn** [comment]
Please merge this.  This issue is still outstanding.

**Comment by pszemus** [comment]
Can someone take a look and merge this PR? I've tested it with Sonar 8.9.7.52159 and it works well.

**Comment by rimuln** [comment]
yes we are on 9.9.0 and stil it works for me.

**Comment by mamayadi** [comment]
@arkanjoms can you merge this PR ?

**Review by arkanjoms — APPROVED** [review]

**Pull request merged**
